# Generated by Django 3.1.7 on 2021-04-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210414_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='published',
            field=models.DateField(),
        ),
    ]
